[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hcs4os"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "openpyxl",
    "dspy"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hcs4os*"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.json", "*.csv", "*.xml", "*.xlsx"]