[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hcs4os"
version = "0.2.0"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "openpyxl",
    "dspy"
]

[tool.setuptools.packages.find]
where = ["./hcs4os"]
include = ["classification_system*", "dataloaders*", "shared*", "data*", "agents*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.csv", "*.xml", "*.xlsx"]