[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hcs4os"
version = "0.1.0"
dependencies = [
    "pandas",
    "openpyxl"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["classification_system*", "dataloaders*", "shared*", "data*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.csv", "*.xml", "*.xlsx"]